#=========================================================================
# .travis.yml
#=========================================================================
# Continuous integration with TravisCI

language: python

python:
  - "3.6"

#-------------------------------------------------------------------------
# Install
#-------------------------------------------------------------------------

install:
  - sudo apt-get install -y graphviz
  # For some reason, the latest setuptools (46.1.1) causes permission
  # denied errors when trying to access site packages (to access scripts
  # like mflowgen-status), so we are pinning to 46.0.0 and waiting to see
  # if they will fix it on their end.
  #
  # Also need to pin pip (20.0.2) because (20.1) makes pyupgrade exit 1
  # for whatever reason. We are pinning for now and waiting to see if they
  # fix it on their end.

#   - pip install --upgrade pip==20.0.2 setuptools==46.0.0 twine
#   - pip install --requirement requirements/ci.txt
#   - pip install .
#   - pip list

#-------------------------------------------------------------------------
# Tests
#-------------------------------------------------------------------------

script:

  - echo Every '[glob' command must be preceded by '[lsort' or this test will fail.

  - |
    exit_status=0
    for f in `find * -name \*.tcl`; do
       ERR=
       grep -H '\[glob ' $f | grep -v '\[lsort ' > /tmp/tmp$$ && ERR=true
       if [ "$ERR" ]; then
         echo BAD FILE $f; cat /tmp/tmp$$; exit_status=13; echo ""
         /bin/rm /tmp/tmp$$
       fi
    done
    exit $exit_status


  # - find * -name \*.tcl -exec grep '[glob ' {} \; | grep -v '[lsort ' && exit 13
