#=========================================================================
# Cadence Innovus
#=========================================================================
# Author : Alex Carsello
# Date   : Dec. 13, 2023
#

name: cadence-innovus-gen-design-files

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design.checkpoint
  - innovus-foundation-flow

outputs:
  - design.gds.gz
  - design-merged.gds
  - design.lvs.v
  - design.vcs.v
  - design.vcs.pg.v
  - design.lef
  - design.pt.sdc
  - design.sdf
  - design.virtuoso.v
  - design.def.gz

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - ln -sf inputs/innovus-foundation-flow
  - innovus -overwrite -64 -nowin -init START.tcl -log logs/run.log

  # Outputs
  - cd outputs
  - ln -sf ../results/*-merged.gds        design-merged.gds
  - ln -sf ../results/*.lvs.v             design.lvs.v
  - ln -sf ../results/*.vcs.v             design.vcs.v
  - ln -sf ../results/*.vcs.pg.v          design.vcs.pg.v
  - ln -sf ../results/*.lef               design.lef
  - ln -sf ../results/*.pt.sdc            design.pt.sdc
  - ln -sf ../results/*.virtuoso.v        design.virtuoso.v
  - ln -sf ../results/*.def.gz            design.def.gz

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  order:
    - generate-results.tcl

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - innovus -overwrite -64
    -init innovus-foundation-flow/custom-scripts/run-debug.tcl
    -log logs/debug.log

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'innovus' )                         # tool check
  - assert File( 'inputs/innovus-foundation-flow' )  # must exist
  - assert File( 'inputs/adk' )                      # must exist
  - assert File( 'inputs/design.checkpoint' )        # must exist

postconditions:

  - assert File( 'outputs/design-merged.gds' )   # must exist
  - assert File( 'outputs/design.lvs.v' )        # must exist
  - assert File( 'outputs/design.vcs.v' )        # must exist
  - assert File( 'outputs/design.vcs.pg.v' )     # must exist
  - assert File( 'outputs/design.lef' )          # must exist
  - assert File( 'outputs/design.pt.sdc' )       # must exist
  - assert File( 'outputs/design.virtuoso.v' )   # must exist
  - assert File( 'outputs/design.def.gz' )       # must exist


