#=========================================================================
# Mentor Calibre LVS
#=========================================================================
# Author : Christopher Torng
# Date   : November 5, 2019
#

name: mentor-calibre-lvs

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

inputs:
  - adk
  - design_merged.gds
  - design.lvs.v
  - rules.svrf

outputs:
  - lvs.report
  - design.schematic.spi

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - if [ -z "{lvs_hcells_file}" ]; then export lvs_use_hcells=0; else export lvs_use_hcells=1; fi
  - envsubst < lvs.runset.template > lvs.runset
  - if [ ! -f inputs/*.svrf ]; then touch inputs/rules.svrf; fi
  - cat inputs/*.lvs.v > merged.v
  - calibre -gui -lvs -batch -runset lvs.runset
  - mkdir -p outputs && cd outputs
  - ln -sf ../lvs.report
  - ln -sf ../_merged.v.sp design.schematic.spi

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  design_name: undefined
  # path to hcells file if required
  lvs_hcells_file: ""
  # net names to connect in a quoted, space-separated list, e.g. "VDD VSS"
  lvs_connect_names: ""

#-------------------------------------------------------------------------
# Debug
#-------------------------------------------------------------------------

debug:
  - calibredrv -m inputs/design_merged.gds \
               -l inputs/adk/calibre.layerprops \
               -rve -lvs svdb

#-------------------------------------------------------------------------
# Assertions
#-------------------------------------------------------------------------

preconditions:

  - assert Tool( 'calibre' )
  - assert File( 'inputs/adk' )
  - assert File( 'inputs/design_merged.gds' )
  - assert File( 'inputs/design.lvs.v' )


