#=========================================================================
# ASIC Design Kit -- Skywater130
#=========================================================================
# Author : Alex Carsello
# Date   : July 12, 2022
#

name: skywater-130nm

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - adk

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  # If standard view is selected, download the full pkg (~17MB)
  - if [[ x{adk_view} == xview-standard ]]; then
      wget https://github.com/mflowgen/skywater-130nm/archive/open_pdks.zip;
      unzip open_pdks.zip;
      mv skywater-130nm-open_pdks/{adk_view} {adk_view};
    fi
  # Set up the outputs
  - mkdir -p outputs && cd outputs
  - ln -sf ../{adk_view} adk

#-------------------------------------------------------------------------
# Parameters
#-------------------------------------------------------------------------

parameters:
  adk: skywater-130nm
  adk_view: view-standard

#-------------------------------------------------------------------------
# Special mflowgen tags
#-------------------------------------------------------------------------

sandbox: False


