#=========================================================================
# OpenROAD Flow Scripts
#=========================================================================
# This node outputs design files as a gzipped tarball for consumption by
# downstream OpenROAD Flow Scripts nodes.
#
# A design node in the OpenROAD Flow Scripts methodology has the following
# hierarchy:
#
# orfs-design
#     ├── nangate45
#     │   └── ibex
#     │       ├── config.mk
#     │       ├── constraint.sdc
#     │       ├── metadata-base-ok.json
#     │       └── rules-base.json
#     └── src
#         └── ibex
#             ├── ibex_alu.v
#             ├── ibex_branch_predict.v
#             ├── ibex_compressed_decoder.v
#             ├── ibex_controller.v
#             ├── ibex_core.v
#             ├── ibex_counter.v
#             ├── ibex_cs_registers.v
#             ├── ibex_csr.v
#             ├── ibex_decoder.v
#             ├── ibex_dummy_instr.v
#             ├── ibex_ex_block.v
#             ├── ibex_fetch_fifo.v
#             ├── ibex_icache.v
#             ├── ibex_id_stage.v
#             ├── ibex_if_stage.v
#             ├── ibex_load_store_unit.v
#             ├── ibex_multdiv_fast.v
#             ├── ibex_multdiv_slow.v
#             ├── ibex_pmp.v
#             ├── ibex_prefetch_buffer.v
#             ├── ibex_register_file_ff.v
#             ├── ibex_register_file_fpga.v
#             ├── ibex_register_file_latch.v
#             ├── ibex_wb_stage.v
#             ├── LICENSE
#             ├── prim_badbit_ram_1p.v
#             ├── prim_clock_gating.v
#             ├── prim_generic_clock_gating.v
#             ├── prim_generic_ram_1p.v
#             ├── prim_lfsr.v
#             ├── prim_ram_1p.v
#             ├── prim_secded_28_22_dec.v
#             ├── prim_secded_28_22_enc.v
#             ├── prim_secded_39_32_dec.v
#             ├── prim_secded_39_32_enc.v
#             ├── prim_secded_72_64_dec.v
#             ├── prim_secded_72_64_enc.v
#             ├── prim_xilinx_clock_gating.v
#             └── README.md
#
# These files will be placed into the "flow/design" directory within the
# downstream docker container. Please refer to the OpenROAD Flow Scripts
# documentation for details on what each file does.
#
# Author : Dolendra Vikas Addepalli
# Date   : July 02, 2024
#

name: orfs-design

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - orfs-design

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - mkdir -p outputs && cd outputs
  - ln -sf ../orfs-design


